// <auto-generated />
using System;
using System.Collections.Generic;
using JurisNexo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JurisNexo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116020920_AddWhatsAppServicesEntities")]
    partial class AddWhatsAppServicesEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JurisNexo.Domain.Common.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConsentDeniedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConsentGrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConsentRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConsentRevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLead")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Phone");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("UserId");

                    b.ToTable("Interactions", (string)null);
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualCloseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedToUserName")
                        .HasColumnType("text");

                    b.Property<string>("CaseDescription")
                        .HasColumnType("text");

                    b.Property<string>("CaseType")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("EstimatedValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ExpectedCloseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstContactAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasExistingCase")
                        .HasColumnType("boolean");

                    b.Property<int>("InteractionCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastContactDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LostReason")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PipelineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PipelineId1")
                        .HasColumnType("uuid");

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<float?>("Probability")
                        .HasColumnType("real");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("ResponseTime")
                        .HasColumnType("interval");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("StageId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tags")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ContactId");

                    b.HasIndex("PipelineId");

                    b.HasIndex("PipelineId1");

                    b.HasIndex("StageId");

                    b.HasIndex("TenantId", "PipelineId", "StageId", "Position");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LeadId");

                    b.HasIndex("TenantId");

                    b.ToTable("LeadActivities", (string)null);
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LeadId");

                    b.HasIndex("TenantId");

                    b.ToTable("LeadNotes", (string)null);
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Pipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsDefault");

                    b.ToTable("Pipelines", (string)null);
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultProbability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInitialStage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLostStage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsWonStage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("PipelineId", "Position");

                    b.ToTable("Stages", (string)null);
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<double>("AvgResponseTimeMinutes")
                        .HasColumnType("double precision");

                    b.Property<double>("ConversionRate")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmailVerificationCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerificationCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SpecializationsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Appointment", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasColumnType("text");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MeetLink")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CaseId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TenantId");

                    b.HasDiscriminator().HasValue("Appointment");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.AppointmentParticipant", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasIndex("AppointmentId");

                    b.HasDiscriminator().HasValue("AppointmentParticipant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.AuditLog", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("TenantId")
                                .HasColumnName("AuditLog_TenantId");
                        });

                    b.HasDiscriminator().HasValue("AuditLog");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Case", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("CaseNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("boolean");

                    b.Property<string>("PracticeArea")
                        .HasColumnType("text");

                    b.Property<Guid?>("ResponsibleLawyerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ClientId");

                    b.HasIndex("ResponsibleLawyerId");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Description")
                                .HasColumnName("Case_Description");

                            t.Property("Status")
                                .HasColumnName("Case_Status");

                            t.Property("Title")
                                .HasColumnName("Case_Title");
                        });

                    b.HasDiscriminator().HasValue("Case");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.CaseEvent", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasIndex("CaseId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("CaseId")
                                .HasColumnName("CaseEvent_CaseId");

                            t.Property("CreatedBy")
                                .HasColumnName("CaseEvent_CreatedBy");

                            t.Property("CreatedByUserId")
                                .HasColumnName("CaseEvent_CreatedByUserId");

                            t.Property("Description")
                                .HasColumnName("CaseEvent_Description");

                            t.Property("Title")
                                .HasColumnName("CaseEvent_Title");

                            t.Property("Type")
                                .HasColumnName("CaseEvent_Type");
                        });

                    b.HasDiscriminator().HasValue("CaseEvent");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.ContactDocument", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ContactId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Name")
                                .HasColumnName("ContactDocument_Name");
                        });

                    b.HasDiscriminator().HasValue("ContactDocument");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Conversation", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsappChatId")
                        .HasColumnType("text");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ContactId");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("ContactId")
                                .HasColumnName("Conversation_ContactId");

                            t.Property("Status")
                                .HasColumnName("Conversation_Status");
                        });

                    b.HasDiscriminator().HasValue("Conversation");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.ConversationTransfer", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransferredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("ConversationId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.HasDiscriminator().HasValue("ConversationTransfer");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadAssignment", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignmentReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.HasIndex("LeadId");

                    b.HasIndex("TenantId");

                    b.HasDiscriminator().HasValue("LeadAssignment");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadConversionFunnel", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<TimeSpan>("DurationInPreviousStage")
                        .HasColumnType("interval");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransitionedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("LeadId")
                                .HasColumnName("LeadConversionFunnel_LeadId");
                        });

                    b.HasDiscriminator().HasValue("LeadConversionFunnel");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadFollowUpTask", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.HasIndex("LeadId");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("LeadId")
                                .HasColumnName("LeadFollowUpTask_LeadId");
                        });

                    b.HasDiscriminator().HasValue("LeadFollowUpTask");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadQualificationAnswer", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.HasIndex("LeadId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("LeadId")
                                .HasColumnName("LeadQualificationAnswer_LeadId");
                        });

                    b.HasDiscriminator().HasValue("LeadQualificationAnswer");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadQualificationQuestion", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("ExpectedResponseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldToMap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.HasIndex("TenantId");

                    b.HasDiscriminator().HasValue("LeadQualificationQuestion");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadRoutingRule", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("IsActive")
                                .HasColumnName("LeadRoutingRule_IsActive");

                            t.Property("Priority")
                                .HasColumnName("LeadRoutingRule_Priority");
                        });

                    b.HasDiscriminator().HasValue("LeadRoutingRule");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadScore", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.HasIndex("LeadId");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("LeadId")
                                .HasColumnName("LeadScore_LeadId");

                            t.Property("Reason")
                                .HasColumnName("LeadScore_Reason");
                        });

                    b.HasDiscriminator().HasValue("LeadScore");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Message", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("SenderType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhatsappMessageId")
                        .HasColumnType("text");

                    b.HasIndex("ConversationId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("ConversationId")
                                .HasColumnName("Message_ConversationId");
                        });

                    b.HasDiscriminator().HasValue("Message");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.MessageTemplate", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Content")
                                .HasColumnName("MessageTemplate_Content");

                            t.Property("Name")
                                .HasColumnName("MessageTemplate_Name");
                        });

                    b.HasDiscriminator().HasValue("MessageTemplate");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.ScheduledMessage", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmationResponse")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("RequestConfirmation")
                        .HasColumnType("boolean");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("ConversationId")
                                .HasColumnName("ScheduledMessage_ConversationId");

                            t.Property("CreatedByUserId")
                                .HasColumnName("ScheduledMessage_CreatedByUserId");

                            t.Property("Notes")
                                .HasColumnName("ScheduledMessage_Notes");

                            t.Property("SentAt")
                                .HasColumnName("ScheduledMessage_SentAt");

                            t.Property("Status")
                                .HasColumnName("ScheduledMessage_Status");
                        });

                    b.HasDiscriminator().HasValue("ScheduledMessage");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Tenant", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Email")
                                .HasColumnName("Tenant_Email");

                            t.Property("IsActive")
                                .HasColumnName("Tenant_IsActive");
                        });

                    b.HasDiscriminator().HasValue("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppContact", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("BusinessCategory")
                        .HasColumnType("text");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfileName")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("SyncStatus")
                        .HasColumnType("text");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.Property<string>("WhatsAppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ContactId");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("ContactId")
                                .HasColumnName("WhatsAppContact_ContactId");

                            t.Property("Description")
                                .HasColumnName("WhatsAppContact_Description");
                        });

                    b.HasDiscriminator().HasValue("WhatsAppContact");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppConversation", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBotEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCustomerMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SessionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SessionStatus")
                        .HasColumnType("integer");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsAppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CaseId");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("AssignedToUserId")
                                .HasColumnName("WhatsAppConversation_AssignedToUserId");

                            t.Property("CaseId")
                                .HasColumnName("WhatsAppConversation_CaseId");

                            t.Property("LastMessageAt")
                                .HasColumnName("WhatsAppConversation_LastMessageAt");

                            t.Property("TagsJson")
                                .HasColumnName("WhatsAppConversation_TagsJson");

                            t.Property("UnreadCount")
                                .HasColumnName("WhatsAppConversation_UnreadCount");

                            t.Property("WhatsAppId")
                                .HasColumnName("WhatsAppConversation_WhatsAppId");
                        });

                    b.HasDiscriminator().HasValue("WhatsAppConversation");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppMedia", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("BlobStorageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhatsAppMediaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("MessageId");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("MimeType")
                                .HasColumnName("WhatsAppMedia_MimeType");
                        });

                    b.HasDiscriminator().HasValue("WhatsAppMedia");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppMessage", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("MediaType")
                        .HasColumnType("text");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("ProviderMessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WhatsAppConversationId")
                        .HasColumnType("uuid");

                    b.Property<string>("WhatsAppMessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("WhatsAppConversationId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Content")
                                .HasColumnName("WhatsAppMessage_Content");

                            t.Property("MediaUrl")
                                .HasColumnName("WhatsAppMessage_MediaUrl");

                            t.Property("MetadataJson")
                                .HasColumnName("WhatsAppMessage_MetadataJson");

                            t.Property("SentAt")
                                .HasColumnName("WhatsAppMessage_SentAt");

                            t.Property("Status")
                                .HasColumnName("WhatsAppMessage_Status");

                            t.Property("Type")
                                .HasColumnName("WhatsAppMessage_Type");
                        });

                    b.HasDiscriminator().HasValue("WhatsAppMessage");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppTemplate", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComponentsJson")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Category")
                                .HasColumnName("WhatsAppTemplate_Category");

                            t.Property("Content")
                                .HasColumnName("WhatsAppTemplate_Content");

                            t.Property("Name")
                                .HasColumnName("WhatsAppTemplate_Name");

                            t.Property("Status")
                                .HasColumnName("WhatsAppTemplate_Status");
                        });

                    b.HasDiscriminator().HasValue("WhatsAppTemplate");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppWebhookLog", b =>
                {
                    b.HasBaseType("JurisNexo.Domain.Common.BaseEntity");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid");

                    b.HasIndex("TenantId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("ErrorMessage")
                                .HasColumnName("WhatsAppWebhookLog_ErrorMessage");
                        });

                    b.HasDiscriminator().HasValue("WhatsAppWebhookLog");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Contact", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Contacts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Interaction", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Contact", "Contact")
                        .WithMany("Interactions")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contact");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Lead", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.User", "AssignedToUser")
                        .WithMany("AssignedLeads")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JurisNexo.Domain.Entities.Contact", "Contact")
                        .WithMany("Leads")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JurisNexo.Domain.Entities.Pipeline", "Pipeline")
                        .WithMany()
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JurisNexo.Domain.Entities.Pipeline", null)
                        .WithMany("Leads")
                        .HasForeignKey("PipelineId1");

                    b.HasOne("JurisNexo.Domain.Entities.Stage", "Stage")
                        .WithMany("Leads")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Contact");

                    b.Navigation("Pipeline");

                    b.Navigation("Stage");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadActivity", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JurisNexo.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.Lead", "Lead")
                        .WithMany("Activities")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Lead");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadNote", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Lead");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Pipeline", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Stage", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Pipeline", "Pipeline")
                        .WithMany("Stages")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pipeline");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.User", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId");

                    b.HasOne("JurisNexo.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedAppointments")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.AppointmentParticipant", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Participants")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Case", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Contact", "Client")
                        .WithMany("Cases")
                        .HasForeignKey("ClientId");

                    b.HasOne("JurisNexo.Domain.Entities.User", "ResponsibleLawyer")
                        .WithMany("ResponsibleCases")
                        .HasForeignKey("ResponsibleLawyerId");

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Cases")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ResponsibleLawyer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.CaseEvent", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Case", "Case")
                        .WithMany("Events")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.ContactDocument", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Contact", "Contact")
                        .WithMany("Documents")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("JurisNexo.Domain.Entities.Contact", "Contact")
                        .WithMany("Conversations")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Contact");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.ConversationTransfer", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.WhatsAppConversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadAssignment", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Lead", "Lead")
                        .WithMany("AssignmentHistory")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadConversionFunnel", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadFollowUpTask", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Lead", "Lead")
                        .WithMany("FollowUpTasks")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadQualificationAnswer", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Lead", "Lead")
                        .WithMany("Answers")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.LeadQualificationQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Question");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadQualificationQuestion", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadRoutingRule", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.LeadScore", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Lead", "Lead")
                        .WithMany("ScoreHistory")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Message", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.MessageTemplate", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.ScheduledMessage", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.WhatsAppConversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurisNexo.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("Conversation");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppContact", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppConversation", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("JurisNexo.Domain.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId");

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Case");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppMedia", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.WhatsAppMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId");

                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppMessage", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.WhatsAppConversation", "WhatsAppConversation")
                        .WithMany("Messages")
                        .HasForeignKey("WhatsAppConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WhatsAppConversation");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppTemplate", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppWebhookLog", b =>
                {
                    b.HasOne("JurisNexo.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Contact", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Conversations");

                    b.Navigation("Documents");

                    b.Navigation("Interactions");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Lead", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Answers");

                    b.Navigation("AssignmentHistory");

                    b.Navigation("FollowUpTasks");

                    b.Navigation("ScoreHistory");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Pipeline", b =>
                {
                    b.Navigation("Leads");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Stage", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedLeads");

                    b.Navigation("CreatedAppointments");

                    b.Navigation("ResponsibleCases");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Case", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Contacts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("JurisNexo.Domain.Entities.WhatsAppConversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
