/**
 * Database types - generated by Supabase CLI
 * Run: pnpm --filter @jurisnexo/db generate
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string;
          name: string;
          slug: string;
          plan: 'trial' | 'basic' | 'pro' | 'enterprise';
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          plan?: 'trial' | 'basic' | 'pro' | 'enterprise';
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          plan?: 'trial' | 'basic' | 'pro' | 'enterprise';
          settings?: Json;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          tenant_id: string;
          email: string;
          full_name: string;
          role: 'admin' | 'lawyer' | 'secretary' | 'paralegal';
          avatar_url: string | null;
          oab_number: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          email: string;
          full_name: string;
          role?: 'admin' | 'lawyer' | 'secretary' | 'paralegal';
          avatar_url?: string | null;
          oab_number?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          full_name?: string;
          role?: 'admin' | 'lawyer' | 'secretary' | 'paralegal';
          avatar_url?: string | null;
          oab_number?: string | null;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          old_data: Json | null;
          new_data: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          old_data?: Json | null;
          new_data?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: never;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      plan_type: 'trial' | 'basic' | 'pro' | 'enterprise';
      user_role: 'admin' | 'lawyer' | 'secretary' | 'paralegal';
    };
  };
}
